# Site settings
title: matematika.org
description: Математика - изучаем предмет применительно к современным потребностям в программировании и анализе данных
keywords: Математика, Статистика, Теория вероятности, Программирование, Machine Learning, Deep Learning, Reinforcement Learning, BigData, Hadoop, Spark, Kafka, BlockChain, IoT

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://matematika.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
