name: Build
on: 
  pull_request:
    branches:
    - gh-pages
  push:
    branches:
    - gh-pages

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker container image
      run: docker build ./ -f ./Dockerfile -t marley/jsdev.org:latest
